POST http://localhost:3000/api/QuanLyNguoiDung/DangKy


//------------------Quan Ly Nguoi Dung------------------
###
//Đăng kí
POST http://localhost:3000/api/QuanLyNguoiDung/DangKy
Content-Type: application/json

{
  "taiKhoan": "tanlon",
  "matKhau": "1234567",
  "email": "loi@gmail.com",
  "soDt": "512522222",
  "hoTen": "string",
  "diaChi": "alalalalal"
}

###
//đăng nhập
POST http://localhost:3000/api/QuanLyNguoiDung/DangNhap
Content-Type: application/json

{
  "taiKhoan": "bangphi", 
  "matKhau": "1234597s1Ba"
  //"taiKhoan": "tanlon", 
  //"matKhau": "1234567"
}

###
//lấy profile
GET http://localhost:3000/api/QuanLyNguoiDung/NguoiDung/ThongTin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNjOTBjZmEwNTJjNmJhZGQwM2ZkZjMiLCJpYXQiOjE2NDgxNDA4ODF9.BHwFZbRUeluCC99OANjr9hQgv_eR__rTX2KK3tagX4g

###
//Người dùng thích sản phẩm
POST http://localhost:3000/api/QuanLyNguoiDung/NguoiDung/Like/623dc6723919427cfa85d22e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNkYzY3MTM5MTk0MjdjZmE4NWQyMjUiLCJpYXQiOjE2NDgyMTU3MDZ9.GBfbVP4HLBe-jB1L54h-wU5EA1Q46l87VpwTigAKLC8

###
//Người dùng comment sản phẩm
POST http://localhost:3000/api/QuanLyNguoiDung/Comment/623dc6723919427cfa85d22e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjNkYzY3MTM5MTk0MjdjZmE4NWQyMjUiLCJpYXQiOjE2NDgyMTU3MDZ9.GBfbVP4HLBe-jB1L54h-wU5EA1Q46l87VpwTigAKLC8

{
  
}


//------------------Quan Ly Categories------------------
###
//lấy tất cả categori
GET http://localhost:3000/api/QuanLyCategoreis/LayToanBo


//------------------Quan Ly Sản Phẩm------------------
###
//lấy tất cả categori
// ?limit=1?skip=1?sor
GET http://localhost:3000/api/QuanLySanPham/LayTatCaSanPham?categories=/nu_gioi/ao/ao_thun&limit=1


###
//lấy sản phẩm theo tên
// ?tenSanPham
GET http://localhost:3000/api/QuanLySanPham/TimSanPhamTheoTen?tenSanPham=


###
//lấy sản phẩm theo tên
// ?tenSanPham
GET http://localhost:3000/api/QuanLySanPham/TimChiTietSanPham/623b64daff48d774918cd745



###
//lấy sản phẩm theo tên
// ?tenSanPham
POST http://localhost:3000/api/QuanLySanPham/ThemSanPham
Content-Type: application/json

{
  "categories": "/nu_gioi/ao/ao_thun",
  "giaTien": 20000000,
  "phanTranTramSale": 20,
  "sale": true,
  "tenSanPham": "Áo Dio",
  "mauSac": [{
    "tenMauSac": "#ffffff",
    "size": [{
      "tenSize": 43,
      "soLuong": 50
    }]
  }]
}
